apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-vmware-vsphere-csi-driver-operator
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: vmware-vsphere-cloud-credentials
    namespace: openshift-cluster-csi-drivers
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
      # FIXME: find a replacement for instanceAdmin, since the CSI driver
      # only needs "compute.instances.[get|attachDisk|DetachDisk]"
      - roles/compute.instanceAdmin
      - roles/compute.storageAdmin
      - roles/iam.serviceAccountUser
    # If set to true, don't check whether the requested
    # roles have the necessary services enabled
    skipServiceCheck: true
