apiVersion: v1
data:
  "csi-migration": "true" # csi-migration feature is only available for vSphere 7.0U1
  "csi-auth-check": "true"
  "online-volume-extend": "true"
  "improved-csi-idempotency": "true"
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: openshift-cluster-csi-drivers
